//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2Field.K2NE.ServiceBroker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K2Field.K2NE.ServiceBroker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve process (with id: {0}). Got {1} results..
        /// </summary>
        internal static string CouldNotRetrieveProcess {
            get {
                return ResourceManager.GetString("CouldNotRetrieveProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field is empty.
        /// </summary>
        internal static string ErrorRequiredEmpty {
            get {
                return ResourceManager.GetString("ErrorRequiredEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be parsed to a Byte..
        /// </summary>
        internal static string NotParseToByte {
            get {
                return ResourceManager.GetString("NotParseToByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be parsed to a Guid..
        /// </summary>
        internal static string NotParseToGuid {
            get {
                return ResourceManager.GetString("NotParseToGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be parsed to a Integer..
        /// </summary>
        internal static string NotParseToInteger {
            get {
                return ResourceManager.GetString("NotParseToInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile with name &quot;{0}&quot; was not found..
        /// </summary>
        internal static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required but is empty..
        /// </summary>
        internal static string RequiredPropertyIsEmpty {
            get {
                return ResourceManager.GetString("RequiredPropertyIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a required property, but does not exist..
        /// </summary>
        internal static string RequiredPropertyNotFound {
            get {
                return ResourceManager.GetString("RequiredPropertyNotFound", resourceCulture);
            }
        }
    }
}
