== ChangeLog

=== v1.4.1
- Restructure of files
- Backwards compatibility (.Create() vs .Add())

=== v1.4
- Added URM service objects

=== v1.3.1
- Fix a silly copy/paste mistake

=== v1.3
- Added a UM Get Users Service Object. This can be used to replace the UMUser GetUsers method, which speeds up a number of things because this filters directly on the backend.
  It also shows that we can convert a SQL query to a AD query. it's a bit tricky with all the properties to match, this could be done easier. But we'll see where this functionality goes.
- Added functionality to define MULTIPLE LDAP's. Querying is done in Parallel.For-loop to not wait sequentually.

=== v1.2
- Added Out of office service object
- Added Culture information to identity object.
- Added DefaultClientCredentials to identity object.
- Added WorkingHour configuration Service Object.

=== v1.1.5
- Fixed issue with mutex, not completely resolved but should not run into the issue anymore.s

=== v1.1.4
- Worklist SO - Added 'ExcludeAllocated' flag which will all you to remove the allocated tasks. This is useful if a task is assigned to a group of people and has multiple slots, as at that point the task will show up multiple times (the allocated and opened item).

=== v1.1.3
- Worklist SO - Remove ActivityOverdue column in the WorklistSO as it was not filled and this calculation can be done on the UI side.
- Worklist SO - Fill the Originaldestination column with the Allocated User field.
- Worklist SO - Include option to retrieve shared Worklist items, these are the out of office worklist items for other users. Must be provided as input property.

=== v1.1.2
- Changed 'ProcesInstanceId' to an Number, it was a Text property. This made linking with application data difficult.

=== v1.1.1
- Changed Active Directory SearchUser method to a 'StartWith' type of search, not a contains.

=== v1.1
- Added Active Directory Service Object which includes functionality to get Details, get Users and SearchUsers. Main reason for this SMO is the SearchUsers.

=== V1.0
- First version